# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyhP9LfOpH3tuh520zLdna2oRvsJHWzR
"""

import matplotlib.pyplot as plt
import seaborn as sns
tips=sns.load_dataset('tips')
sns.barplot(x='day',y='total_bill',tips=)
plt.xlabel('mpg')
plt.ylabel('weight')
plt.title('histogram')
plt.show()

import matplo

import pandas as pd
data=pd.read_csv("/content/mtcars.csv")
print(data)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
red
sns.histplot(df['wt'],bins=10,color='blue',alpha=0.7)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.hist(df['wt'],bins=10,color='blue',alpha=0.7)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.histplot(df['wt'],bins=10,color='blue',alpha=0.7)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.barplot(x='wt',y='am',data=df)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.histplot(df['wt'],bins=10,color='blue',alpha=0.7)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('hist')
plt.grid(True)
plt.show()



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.scatterplot(x='wt',y='am',data=df,alpha=0.7)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.boxplot(x='wt',y='am',data=df)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('box')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("mtcars")
sns.scatterplot(x='mt',y='am',data=data)
plt.xlabel('mt')
plt.ylabel('am')
plt.title('scatter')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/mtcars.csv")
sns.boxplot(x='wt',y='am',data=df)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('box')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/wine.csv")
sns.boxplot(x='Ash',y='Acl',data=df)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('box')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/wine.csv")
sns.scatterplot(x='Ash',y='Acl',data=df,alpha=0.7)
plt.xlabel('Ash')
plt.ylabel('Asl')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/wine.csv")
sns.histplot(df['Ash'],bins=10,color='blue',alpha=0.7)
plt.xlabel('Ash')
plt.ylabel('frequency')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/wine.csv")
sns.histplot(df['Ash'],bins=10,color='blue',alpha=0.7)
plt.xlabel('Ash')
plt.ylabel('frequency')
plt.title('hist')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/wine.csv")
sns.barplot(x='Ash',y='Acl',data=df)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('box')
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/tips (2).csv")
sns.boxplot(x='day',y='time',data=df)
plt.xlabel('wt')
plt.ylabel('am')
plt.title('box')
plt.grid(True)
plt.show()